### ISSUE TITLE
Does this library clears input type file too?

### ISSUE THREAD

**Issue by RogelioGaytan** [waldirpereira/angular-reset-on#1]
Very straigth forward question

can it clear a input type file?

**Comment by waldirpereira** [comment]
No, @RogelioGaytan . Unfortunately, file input doesn't have the ng-model directive. You can check this at AngularJS [doc](https://docs.angularjs.org/api/ng/directive/input#overview):

> Note: Not every feature offered is available for all input types. Specifically, data binding and event handling via ng-model is unsupported for input[file].

This directive needs the ng-model directive to run.
To clear an input file you have to try a workaround.

Wish you luck. I'm closing this issue.
Regards,
Waldir
